version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/docs"
    schedule:
      interval: "weekly"
    groups:
      docs-pip:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/bindings/python"
    schedule:
      interval: "weekly"
    groups:
      python-pip:
        patterns:
          - "*"
